# Automatically generated by: ros2nix --distro noetic
{ lib, buildRosPackage, catkin, cv-bridge, dynamic-reconfigure, image-transport, message-generation, message-runtime, nav-msgs, roscpp, rospy, sensor-msgs, std-msgs, tf, tf2-geometry-msgs, tf2-ros, visualization-msgs, pangolin, eigen, fetchFromGitHub }:
buildRosPackage {
  pname = "ros-noetic-orb-slam3-ros";
  version = "0.0.1";

  # src = fetchFromGitHub {
  #   owner = "SCOTT-HAMILTON";
  #   repo = "orb_slam3_ros";
  #   rev = "0e73edcca7a235175ab4e62d9b800385d74d64bc";
  #   sha256 = "sha256-r4iCvqn6HZaNz6Sd66PEzobk80XXVcFadvXQHIITCAc=";
  # };
  src = ./.;

  buildType = "catkin";
  buildInputs = [ catkin message-generation eigen ];
  propagatedBuildInputs = [ cv-bridge dynamic-reconfigure image-transport message-runtime nav-msgs roscpp rospy sensor-msgs std-msgs tf tf2-geometry-msgs tf2-ros visualization-msgs pangolin ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "ORB SLAM3 ROS implementation.";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
