# Automatically generated by: ros2nix --distro noetic
{ lib, buildRosPackage, catkin, cv-bridge, dynamic-reconfigure, image-transport, message-generation, message-runtime, nav-msgs, roscpp, rospy, sensor-msgs, std-msgs, tf, tf2-geometry-msgs, tf2-ros, visualization-msgs, pangolin, eigen, fetchFromGitHub }:
buildRosPackage {
  pname = "ros-noetic-orb-slam3-ros";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "SCOTT-HAMILTON";
    repo = "orb_slam3_ros";
    rev = "84a20dbd02b6aad480e360ced229002f33d28a3b";
    sha256 = "sha256-bUGxfeIGrfznsB3ptKkzQKd4Vg3ZJ1Rm6ZZwtnt8vkc=";
  };

  buildType = "catkin";
  buildInputs = [ catkin message-generation eigen ];
  propagatedBuildInputs = [ cv-bridge dynamic-reconfigure image-transport message-runtime nav-msgs roscpp rospy sensor-msgs std-msgs tf tf2-geometry-msgs tf2-ros visualization-msgs pangolin ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "ORB SLAM3 ROS implementation.";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
